name = 'Léon 2025'
license = 'MIT'
licenselink = 'https://github.com/owner/repo/LICENSE'
description = 'Léon's Theme'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/leonmelein/leonmelein'


# If the theme has a single author
[author]
  name = 'Léon Melein'
  homepage = 'leon@leonmelein.nl'
